name: nutrition_ai
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

# After adding dependencies, please run the following commands at the project's root:
# flutter packages get
# flutter packages upgrade

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logos/
