name: nutrimind
description: An app that generates personalized meal plans tailored to the user's body, lifestyle, and preferences to help them achieve their goals.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.18.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.3
  provider: ^6.0.5
  firebase_storage: ^11.6.0
  cloud_functions: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logos/logo_icon.png"

flutter_native_splash:
  image: assets/images/logos/logo.png
  color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logos/
